# 第一题

In [67]:
import numpy as np

# 1. 创建从1到12的一维等差数组（arange左闭右开，所以结束值设为13）
arr = np.arange(1, 13)
# 2. 重塑为3行4列的二维数组
arr_2d = arr.reshape(3, 4)

# 3. 分别打印维度、形状、元素总个数
print("数组维度（ndim）：", arr_2d.ndim)
print("数组形状（shape）：", arr_2d.shape)
print("元素总个数（size）：", arr_2d.size)

数组维度（ndim）： 2
数组形状（shape）： (3, 4)
元素总个数（size）： 12


# 第二题

In [68]:
import numpy as np

# 1. 创建包含浮点数的NumPy数组
arr_float = np.array([1.5, 2.6, 3.7, 4.8])

# 打印转换前的数组及其数据类型名称
print("转换前的数组：", arr_float)
print("转换前的数据类型名称：", arr_float.dtype.name)

# 2. 使用astype()转换为32位整数
arr_int = arr_float.astype(np.int32)

# 打印转换后的数组及其数据类型名称
print("转换后的数组：", arr_int)
print("转换后的数据类型名称：", arr_int.dtype.name)

转换前的数组： [1.5 2.6 3.7 4.8]
转换前的数据类型名称： float64
转换后的数组： [1 2 3 4]
转换后的数据类型名称： int32


# 第三题

In [69]:
import numpy as np

# 创建题目给定的二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 切片操作：前两行（索引0~1），第2~3列（索引1~2，左闭右开）
sub_arr = arr[0:2, 1:3]

# 打印结果
print(sub_arr)

[[2 3]
 [6 7]]


# 第四题

In [70]:
import numpy as np

# 创建给定的一维数组
arr = np.array([10, 15, 20, 25, 30, 35])

# 1. 花式索引：用索引列表提取第1、3、5个元素（索引为0,2,4）
fancy_index_result = arr[[0, 2, 4]]
print("花式索引结果：", fancy_index_result)

# 2. 布尔索引：提取所有大于20的元素
bool_index_result = arr[arr > 20]
print("布尔索引结果：", bool_index_result)

花式索引结果： [10 20 30]
布尔索引结果： [25 30 35]


# 第五题

In [71]:
import numpy as np

# 创建形状为(3, 4)的全0数组
arr_a = np.zeros((3, 4))
# 创建一维数组
arr_b = np.array([1, 2, 3, 4])
# 利用广播机制相加
result = arr_a + arr_b
# 打印结果
print(result)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


# 第六题

In [72]:
import numpy as np

# 定义题目给定的数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

# 1. 计算数组x中每个元素的平方根
sqrt_x = np.sqrt(x)
print("x的平方根数组：", sqrt_x)

# 2. 结合平方根数组与数组y，取对应位置的最大值
result = np.maximum(sqrt_x, y)
print("对应位置的最大值：", result)

x的平方根数组： [1. 2. 3. 4.]
对应位置的最大值： [2. 2. 4. 5.]


# 第七题

In [73]:
import numpy as np

# 创建形状为(2, 3, 4)的三维数组
arr = np.arange(24).reshape((2, 3, 4))

# 使用transpose()方法转换轴顺序为(1, 0, 2)
arr_transposed = arr.transpose((1, 0, 2))

# 打印转换后新数组的形状
print(arr_transposed.shape)

(3, 2, 4)


# 第八题

In [74]:
import numpy as np

# 定义题目给定的数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

# 使用np.where()按条件选择元素
result = np.where(arr_con, arr_x, arr_y)

print(result)

[1 6 7]


# 第九题

In [75]:
import numpy as np

# 创建二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

# 1. 计算所有元素的算术平均值
mean_value = arr.mean()
print("所有元素的算术平均值：", mean_value)

# 2. 沿axis=0（列方向）从小到大排序
sorted_arr = np.sort(arr, axis=0)
print("沿axis=0排序后的结果：")
print(sorted_arr)

所有元素的算术平均值： 3.888888888888889
沿axis=0排序后的结果：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


# 第十题

In [76]:
import numpy as np

# 1. 设置随机数种子
np.random.seed(10)

# 2. 生成两个形状为(2, 2)的[0,1)均匀分布随机矩阵
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

# 3. 计算矩阵A和B的点积
dot_product = np.dot(A, B)

# 打印结果（可选，用于验证）
print("矩阵A:")
print(A)
print("矩阵B:")
print(B)
print("矩阵点积结果：")
print(dot_product)

矩阵A:
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B:
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
矩阵点积结果：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
